### ISSUE TITLE
[Request] Automatically detects which conversation is selected in Skype

### ISSUE THREAD

**Issue by marcemv90** [adzm/BusinessCats#1]
Hi,

Many thanks for you app, is great!

Let me suggest you a feature that will improve so much the usability of your application. Would be possible to implement BusinessCats to automatically detects and selects the conversation you have already selected in your Skype for Busines/Lync client?

Kind Regards.

**Comment by jakauppila** [comment]
This would be great, along with a CLI to keybind the pasting of images into that chat
